services:
  php83:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-sql-app
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./:/var/www/html
